name: clean_architecture
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  dio: ^4.0.6
  equatable: ^2.0.5
  floor: ^1.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  ionicons: ^0.2.1
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.3.1
  sqflite: ^2.2.2

dev_dependencies:
  build_runner: ^2.3.2
  floor_generator: ^1.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
